---
id: schoo-readable-code-2015-04
base_name: chapter-7
tags:
- rabbit
- readable-code
- schoo
presentation_date: 2015-04-03
version: 2015.4.3.4
licenses:
- CC BY-SA 4.0
slideshare_id: schoo-readable-code-2015-04
speaker_deck_id: ming-zhu-ridaburukodo-wojie-shuo-zhe-to-xu-nidu-mijie-kou-7zhang-zhi-yu-hurowodu-miyasukusuru
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
